<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cyberarms.IntrusionDetection.Api\Cyberarms.IntrusionDetection.Api.csproj" />
    <ProjectReference Include="..\Cyberarms.IntrusionDetection.Shared\Cyberarms.IntrusionDetection.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.10" />
    <PackageReference Include="System.Management" Version="10.0.10" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.10" />
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Interop.NetFwTypeLib">
      <HintPath>..\Dependencies\Interop\Interop.NetFwTypeLib.dll</HintPath>
    </Reference>
    <Reference Include="Interop.NATUPNPLib">
      <HintPath>..\Dependencies\Interop\Interop.NATUPNPLib.dll</HintPath>
    </Reference>
    <Reference Include="Interop.NETCONLib">
      <HintPath>..\Dependencies\Interop\Interop.NETCONLib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
