<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1416;WFO1000;CS0168;CA2200;SYSLIB0021;SYSLIB0024;CA2022;MSB3042;NU1510;NU1902;NU1903;CS0067;CS8073;CS8600;CS8601;CS8602;CS8603;CS8604;CS8605;CS8609;CS8618;CS8622;CS8625;CS8629;CS8632;CS8765;CS8766;CS8767;CS0414</NoWarn>
  </PropertyGroup>
</Project>
