// <auto-generated />
namespace IDDSCommunity.Agents.WindowsDns;

[global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "10.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
internal static class Resource
{
    private static readonly global::System.Resources.ResourceManager resourceManager =
        new("IDDSCommunity.Agents.WindowsDns.Resource", typeof(Resource).Assembly);

    internal static global::System.Drawing.Bitmap agent15px_dns_dark =>
        (global::System.Drawing.Bitmap)resourceManager.GetObject(nameof(agent15px_dns_dark))!;

    internal static global::System.Drawing.Bitmap agent15px_dns_white =>
        (global::System.Drawing.Bitmap)resourceManager.GetObject(nameof(agent15px_dns_white))!;
}
