<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>PaladinConfig.exe.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cyberarms.Agents.FileMaker\Cyberarms.Agents.FileMaker.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.Agents.FtpServer\Cyberarms.Agents.FtpServer.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.Agents.MailServer\Cyberarms.Agents.MailServer.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.Agents.MySql\Cyberarms.Agents.MySql.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.Agents.Smtp\Cyberarms.Agents.Smtp.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.Agents.SqlServer\Cyberarms.Agents.SqlServer.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.Agents.TerminalServer\Cyberarms.Agents.TerminalServer.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.Agents.WebSecurity\Cyberarms.Agents.WebSecurity.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.Agents.WindowsDns\Cyberarms.Agents.WindowsDns.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Cyberarms.IntrusionDetection.Api\Cyberarms.IntrusionDetection.Api.csproj" />
    <ProjectReference Include="..\Cyberarms.IntrusionDetection.Shared\Cyberarms.IntrusionDetection.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.10" />
    <PackageReference Include="System.Management" Version="10.0.10" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.10" />
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>
</Project>
