using System;
using System.Globalization;
using IDDSCommunity.IntrusionDetection.Service.Notifications;
using IDDSCommunity.IntrusionDetection.Shared.Localization;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace IDDSCommunity.IntrusionDetection.Service.Test;

/// <summary>
/// 驗證 EmailNotificationService 郵件警報內文產製與多語系名稱統一機制。
/// </summary>
[TestClass]
public sealed class EmailNotificationServiceTest
{
    private CultureInfo? originalCulture;
    private CultureInfo? originalUiCulture;

    /// <summary>
    /// 測試初始化，記錄執行緒原始語系。
    /// </summary>
    [TestInitialize]
    public void Setup()
    {
        originalCulture = CultureInfo.CurrentCulture;
        originalUiCulture = CultureInfo.CurrentUICulture;
    }

    /// <summary>
    /// 測試清理，復原執行緒原始語系設定。
    /// </summary>
    [TestCleanup]
    public void Cleanup()
    {
        if (originalCulture != null)
        {
            CultureInfo.CurrentCulture = originalCulture;
        }

        if (originalUiCulture != null)
        {
            CultureInfo.CurrentUICulture = originalUiCulture;
        }

        LanguageManager.Instance.Initialize("auto");
    }

    /// <summary>
    /// 驗證在繁體中文環境下產製之警報郵件 HTML，其標題、欄位與頁尾皆使用純淨正體中文，無英中混用。
    /// </summary>
    [TestMethod]
    public void BuildAlertHtmlBody_TraditionalChinese_UsesPureLocalizedTerms()
    {
        LanguageManager.Instance.Initialize("zh-TW");

        string ip = "77.83.39.11";
        string agentName = "IDDS 社群版";
        string message = $"IP 位址為 {ip} 之用戶端已被解除封鎖。";
        string subject = Strings.Format("IDDS Community: Unlock notification ({0})", ip);

        Assert.AreEqual("IDDS 社群版：解除封鎖通知（77.83.39.11）", subject);

        DateTime fixedTime = new(2026, 9, 11, 0, 55, 50, DateTimeKind.Utc);
        string html = EmailNotificationService.BuildAlertHtmlBody(subject, ip, agentName, message, fixedTime);

        // 標題應為純淨在地化產品名稱，嚴禁出現 "IDDS Community - IDDS 社群版"
        StringAssert.Contains(html, ">🛡️ IDDS 社群版：解除封鎖通知（77.83.39.11）</h2>");
        Assert.IsFalse(html.Contains("IDDS Community - IDDS 社群版", StringComparison.Ordinal));

        // 欄位標籤與全形符號驗證
        StringAssert.Contains(html, "<strong>來源 IP 位址：</strong>");
        StringAssert.Contains(html, "<strong>安全性代理程式：</strong>");
        StringAssert.Contains(html, "<strong>事件發生時間（UTC）：</strong>");

        // 頁尾電子郵件宣告
        StringAssert.Contains(html, "本電子郵件由 IDDS 社群版入侵防禦系統自動發出，請勿直接回覆。");
        Assert.IsFalse(html.Contains("本郵件由 IDDS Community", StringComparison.Ordinal));
    }

    /// <summary>
    /// 驗證在英文環境下產製之警報郵件 HTML，其標題、欄位與頁尾皆使用 IDDS Community 與英文標籤。
    /// </summary>
    [TestMethod]
    public void BuildAlertHtmlBody_English_UsesEnglishTerms()
    {
        LanguageManager.Instance.Initialize("en");

        string ip = "77.83.39.11";
        string agentName = "IDDS Community";
        string message = $"Client with IP address {ip} was unlocked.";
        string subject = Strings.Format("IDDS Community: Unlock notification ({0})", ip);

        Assert.AreEqual("IDDS Community: Unlock notification (77.83.39.11)", subject);

        DateTime fixedTime = new(2026, 9, 11, 0, 55, 50, DateTimeKind.Utc);
        string html = EmailNotificationService.BuildAlertHtmlBody(subject, ip, agentName, message, fixedTime);

        // 標題應為 IDDS Community
        StringAssert.Contains(html, ">🛡️ IDDS Community: Unlock notification (77.83.39.11)</h2>");

        // 欄位標籤驗證
        StringAssert.Contains(html, "<strong>Source IP address:</strong>");
        StringAssert.Contains(html, "<strong>Security agent:</strong>");
        StringAssert.Contains(html, "<strong>Event time (UTC):</strong>");

        // 頁尾宣告
        StringAssert.Contains(html, "This email was automatically generated by IDDS Community intrusion prevention system. Please do not reply directly.");
    }
}