<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IDDSCommunity.IntrusionDetection.Api\IDDSCommunity.IntrusionDetection.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.11" />
    <PackageReference Include="SQLite3MC.PCLRaw.bundle" Version="2.4.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="Microsoft.Extensions.Resilience" Version="10.9.0" />
    <PackageReference Include="System.Management" Version="10.0.11" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.11" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.11" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
  </ItemGroup>
</Project>
